language: php

php:
- 7.2
- nightly

sudo: false

before_script:
- composer self-update
- composer install --prefer-dist;

script:
- ./vendor/bin/parallel-lint ./src/
- ./vendor/bin/phpcs -n -p --standard=PSR2 --extensions=php,twig ./src/
- ./vendor/bin/php-cs-fixer fix -v ./src --dry-run
- ./vendor/bin/phpstan analyse ./src --level=1

notifications:
  email:
  - info@jield.nl

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly