language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --dev --prefer-source;

script:
  - ./vendor/bin/parallel-lint lint ./src/
  - ./vendor/bin/phpcs -n -p --standard=PSR2 ./src/
  - ./vendor/bin/php-cs-fixer fix -v --dry-run ./src/

notifications:
  email: info@jield.nl

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvml